### PR TITLE
Add Pull Request Github workflow

### LINKED ISSUE #80: Culture is not supported
Hello i will run i take this error
image

### LINKED ISSUE #95: Add Github Actions for pull requests
To be able to have at least Unit Tests running on them.

### PR DESCRIPTION
**Pull request by Skrypt**
Fixes #95, Fixes #80

See : 

image

### CODE REVIEW

**Comment by Skrypt** [comment]
Failing because of net6.0

**Comment by Skrypt** [comment]
We would need to multi-target like we do in OC. @bleroy does that make sense or you want to only keep one framework?

**Comment by bleroy** [comment]
It makes sense, but if that's too much work, latest supported by OC wouldn't be terrible

**Comment by Skrypt** [comment]
I could add a common .csproj as we do in OC to add vars for these that we could reuse in each project.

**Comment by Skrypt** [comment]
I will make a different PR for multi-targeting. That's mainly why I had copied the main OC repository structure. To be able to copy/paste these files without having to adapt them for both projects.

**Review by bleroy — APPROVED** [review]

**Comment by Skrypt** [comment]
The CI seems to have problems building it. I'm having the same issue locally but after building it 2 or 3 times it goes away.

**Comment by Skrypt** [comment]
Finally building and passing unit tests!

**Comment by Skrypt** [comment]
Ok I'm done adding commits if you want to merge @bleroy

**Comment by bleroy** [comment]
Thanks for sorting this out!

**Pull request merged**
